---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:
    - name: SELinux was disabled (firing)
      condition: event.payload.alerts[0].labels.alertname == "selinux disabled" and event.payload.alerts[0].status == "firing"
      action:
        debug:
          msg: "disabled on: {{ event.payload.alerts[0].labels.instance }}"

    - name: SELinux was disabled (resolved)
      condition: event.payload.alerts[0].labels.alertname == "selinux disabled" and event.payload.alerts[0].status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.payload.alerts[0].labels.instance }}"

    - name: Network connectiviy issues (firing)
      condition: event.payload.alerts[0].labels.alertname == "NetworkConnectivityIssue" and event.payload.alerts[0].status == "firing"
      action:
        run_job_template:
          name: Reset Network Connection
          organization: ACME
          job_args:
            server: "{{ event.payload.alerts[0].labels.instance | split('.') | first }}"

    - name: Network connectiviy issues (resolved)
      condition: event.payload.alerts[0].labels.alertname == "NetworkConnectivityIssue" and event.payload.alerts[0].status == "resolved"
      action:
        debug:
          msg: "Network issue resolved on: {{ event.payload.alerts[0].labels.instance }}"
          
    - name: Catch all
      condition: event.meta is defined
      action:
        debug:
