---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:
    - name: Network connectiviy issues (firing)
      condition: event.payload.alerts[0].labels.alertname == "NetworkConnectivityIssue" and event.payload.alerts[0].status == "firing"
      action:
        run_workflow_template:
          name: Reset Network Connection
          organization: ACME
          job_args:
            extra_vars:
              server: "{{ event.payload.alerts[0].labels.instance[:8] }}"

    - name: Network connectiviy issues (resolved)
      condition: event.payload.alerts[0].labels.alertname == "NetworkConnectivityIssue" and event.payload.alerts[0].status == "resolved"
      action:
        debug:
          msg: "Network issue resolved on: {{ event.payload.alerts[0].labels.instance }}"
