    - name: SELinux was disabled (firing)
      condition: event.payload.alerts[0].labels.alertname == "selinux disabled" and event.payload.alerts[0].status == "firing"
      action:
        debug:
          msg: "disabled on: {{ event.payload.alerts[0].labels.instance }}"

    - name: SELinux was disabled (resolved)
      condition: event.payload.alerts[0].labels.alertname == "selinux disabled" and event.payload.alerts[0].status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.payload.alerts[0].labels.instance }}"
